site_name: RENware Data API
site_author: 'Petre Iordanescu, RENware Software Systems'
copyright: 'Copyright (c) RENware Software Systems'


nav:
    - Home: 'index.md'



markdown_extensions:
    - admonition
    - tables
    - pymdownx.details
    - pymdownx.superfences:
        custom_fences: #NOTE: is very important to respect syntax ref `-` character at beginning of items (otherwise not right JSON result !)
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_code_format
    - footnotes
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - def_list
    - attr_list
    - md_in_html



#NOTE required to render `mermaid` diagrams
extra_javascript:
  - optionalConfig.js
  - https://unpkg.com/mermaid@9.4.0/dist/mermaid.min.js
  - extra-loader.js



plugins:
    - search
    - include-markdown


#NOTE provide material theme
theme:
    name: material



#NOTE directory where start to search or markdown sources
docs_dir: './doc_src'


#NOTE root directory where to be generated portal (should be `./static_portal`)
site_dir: './static_portal'



#NOTE other useful configurations
use_directory_urls: false # allow link between pages to work properly when used as OFFLINE deployment (ie, static site an "callable" as `file:///...`)


